variable "proxmox_host_ssh_password" {}
variable "proxmox_host_ip_address" {}
variable "proxmox_host_node" {}
variable "hostname" {}
variable "ip_address" {}
variable "gateway" {}
variable "vmid" {}
variable "cores" {}
variable "sockets" {}
variable "memory" {}
variable "disk_size" {}
variable "ipconfig" {}
variable "ssh_user" {}
variable "cloud_init_disk_name" {}
variable "private_ssh_keyname" {}
variable "iso_storage_pool" {}
variable "storage_pool" {}
variable "network_bridge" {}
variable "pve_vm_depends_on" {}
variable "cloud_init_config_file" {}
